import React, { useEffect, useState } from 'react';
import { ShieldAlert } from 'lucide-react';
import { TransactionHistoryView } from './TransactionHistoryView';

interface AdminUser { id: string; email: string; walletAddress?: string; did?: string; createdAt: string; credentialCount: number; status: string; }

export const AdminPortalView: React.FC = () => {
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [flags, setFlags] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [noticeTitle, setNoticeTitle] = useState('');
  const [noticeMessage, setNoticeMessage] = useState('');
  useEffect(() => { Promise.all([fetch('/api/admin/users', { credentials: 'include' }), fetch('/api/admin/fraud-flags', { credentials: 'include' })]).then(async ([usersResponse, flagsResponse]) => { const userData = await usersResponse.json(); const flagData = await flagsResponse.json(); if (!usersResponse.ok) throw new Error(userData.error); setUsers(userData.users); setFlags(flagData.flags || []); }).catch(loadError => setError(loadError instanceof Error ? loadError.message : 'Admin data unavailable')); }, []);
  const revoke = async (userId: string) => { const response = await fetch(`/api/admin/users/${userId}/revoke`, { method: 'POST', credentials: 'include' }); const data = await response.json(); if (!response.ok) return setError(data.error || 'Unable to revoke user'); setUsers(previous => previous.map(user => user.id === userId ? { ...user, status: 'revoked' } : user)); };
  const sendNotification = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/admin/notifications', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: noticeTitle, message: noticeMessage }) }); const data = await response.json(); if (!response.ok) return setError(data.error || 'Unable to send notification'); setNoticeTitle(''); setNoticeMessage(''); setError(null); };
  return <section className="space-y-5"><div className="aegis-panel rounded-2xl p-5"><div className="mb-5 flex items-center gap-3"><ShieldAlert className="h-5 w-5 text-amber-300" /><div><p className="text-[10px] uppercase tracking-[0.2em] text-amber-300">ADMIN CONTROL</p><h2 className="aegis-display mt-1 text-2xl font-semibold text-white">Platform users</h2></div></div>{error && <p className="mb-3 text-sm text-rose-300">{error}</p>}<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-3">Email</th><th className="pb-3">Wallet</th><th className="pb-3">DID</th><th className="pb-3">Credentials</th><th className="pb-3">Status</th><th className="pb-3">Actions</th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="border-t border-white/[0.06] text-slate-300"><td className="py-3">{user.email}</td><td className="py-3 font-mono">{user.walletAddress || '-'}</td><td className="py-3 font-mono">{user.did || '-'}</td><td className="py-3">{user.credentialCount}</td><td className="py-3">{user.status}</td><td className="py-3 flex gap-2"><button onClick={() => setSelected(user.id)} className="text-cyan-300">History</button>{user.status !== 'revoked' && <button onClick={() => void revoke(user.id)} className="text-rose-300">Revoke</button>}</td></tr>)}</tbody></table></div></div>{selected && <TransactionHistoryView adminUserId={selected} />}<div className="aegis-panel rounded-2xl p-5"><h3 className="text-sm font-semibold text-white">Fraud and Sybil flags</h3>{flags.length === 0 ? <p className="mt-3 text-xs text-slate-400">No stored fraud flags.</p> : <div className="mt-3 space-y-2">{flags.map(flag => <div key={flag.id} className="border border-rose-400/20 bg-rose-400/5 p-3 text-xs text-slate-300"><span className="font-mono text-rose-300">{flag.decision}</span> · {flag.timestamp}</div>)}</div>}</div><form onSubmit={sendNotification} className="aegis-panel rounded-2xl p-5"><h3 className="text-sm font-semibold text-white">Notify all users</h3><div className="mt-3 grid gap-2"><input required value={noticeTitle} onChange={event => setNoticeTitle(event.target.value)} placeholder="Notification title" className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-white" /><textarea required value={noticeMessage} onChange={event => setNoticeMessage(event.target.value)} placeholder="Important system or platform update" className="min-h-20 rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-white" /><button className="w-fit rounded-lg bg-amber-300 px-3 py-2 text-xs font-bold text-[#071018]">Send notification</button></div></form></section>;
};